plugins {
    id "com.android.application"
}

android {
    namespace "cloud.pcie.openaiq"
    compileSdk 36

    defaultConfig {
        applicationId "cloud.pcie.openaiq"
        minSdk 24
        targetSdk 36
        versionCode 18
        versionName "2.1.3"
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            signingConfig signingConfigs.debug
            proguardFiles getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro"
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation "com.squareup.okhttp3:okhttp:4.12.0"
    implementation "com.github.gkonovalov.android-vad:webrtc:2.0.10"
    testImplementation "junit:junit:4.13.2"
}
